version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - ./gradlew build
      - mv build/libs/*.jar app.jar
artifacts:
  files:
    - app.jar
    - aws/dev/appspec.yml
    - scripts/**
  discard-paths: yes
cache:
  paths:
    - "/root/.gradle/caches/**/*"